// test/receiptOrganizer.test.mjs
//
// RECEIPT-ORGANIZER-1 (Owner, 2026-09-27): Program Budget > Receipts is To Review (one slip open, the
// rest folded) and Filed (every accepted receipt in folders, all closed until opened), and a vendor's
// logo prints at the top of its drawn receipt. Reference: docs/mockups/receipt-organizer.html. The
// browser behaviour was verified in a harness against the real engine; these hold the rules and wiring.

import { test, before, after } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync, existsSync } from 'node:fs'
import React from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { createServer } from 'vite'
import { PGlite } from '@electric-sql/pglite'
import { pgliteRest } from './helpers/pgliteRest.mjs'

process.env.VITE_SUPABASE_URL ||= 'https://example.supabase.co'
process.env.VITE_SUPABASE_ANON_KEY ||= 'test-anon-key'

const M = await import('../src/lib/budget/receiptModel.js')
const { VENDOR_LOGOS } = await import('../src/lib/budget/vendorLogos.js')
const R = await import('../lib/server/budget/receipts.js')
const E = await import('../lib/server/budget/engine.js')
const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8')
const runnable = (sql) => sql.replace(/NOTIFY pgrst, 'reload schema';/g, '')
const TODAY = '2026-09-27'

test('a vendor finds its logo by name, alias, prefix or first word, and a vendor with none prints its name', () => {
  const cases = {
    Amazon: 'amazon', 'Amazon.com': 'amazon', 'AMZN Mktp US': 'amazon', 'Amazon Business': 'amazon', Michaels: 'michaels-stores',
    'The Home Depot': 'home-depot', 'Costco Wholesale': 'costco', 'Anthropic, PBC': 'anthropic', 'Vercel Inc.': 'vercel', 'Best Buy': 'best-buy',
    // Added 2026-09-27 with the Grok logo: xAI bills as xAI or X.AI Corp.
    xAI: 'grok-xai', 'X.AI Corp': 'grok-xai', Grok: 'grok-xai', 'xAI Holdings': 'grok-xai',
  }
  for (const [vendor, slug] of Object.entries(cases)) assert.equal(M.vendorLogo(vendor), `/vendor-logos/${slug}.png`, vendor)
  for (const vendor of ['Beverly Grove Catering', 'Best Western', 'Office Supplies Co', '', null]) assert.equal(M.vendorLogo(vendor), null, String(vendor))
})

test('every listed logo is on disk as one ink, and the conversion script writes the list', () => {
  assert.ok(VENDOR_LOGOS.length >= 16)
  for (const s of VENDOR_LOGOS) assert.ok(existsSync(new URL(`../public/vendor-logos/${s}.png`, import.meta.url)), s)
  const script = read('scripts/prepare_vendor_logos.py')
  assert.match(script, /src\/lib\/budget\/vendorLogos\.js|'vendorLogos\.js'/)
  assert.match(script, /HEIGHT, INK = 96, \(17, 17, 17\)/)
  assert.match(read('src/lib/budget/vendorLogos.js'), /GENERATED by scripts\/prepare_vendor_logos\.py/)
})

const R1 = { id: 'a', date: '2026-09-03', vendor: 'Amazon', order_number: '112-7730158-4402217', total: 53.49, items: ['Copy Paper', 'Name Badge Labels'], rows: [{ category: 'Printing & Copying', amount: 38.99, statusLabel: 'Recorded', stageLabel: 'Receipt attached' }, { category: 'Supplies & Materials', amount: 14.5, statusLabel: 'Recorded', stageLabel: 'Receipt attached' }] }
const R2 = { id: 'b', date: '2026-09-12', vendor: 'Beverly Grove Catering', order_number: 'INV-20614', total: 496.33, items: ['Lunch'], rows: [{ category: 'Meals & Catering', amount: 496.33, statusLabel: 'Submitted', stageLabel: 'Submitted to Concur' }] }
const R3 = { id: 'c', date: '2026-07-10', vendor: 'Amazon', order_number: '114-0022871', total: 350, items: ['Notebooks'], rows: [{ category: 'Supplies & Materials', amount: 350, statusLabel: 'Reimbursed', stageLabel: 'Reimbursed or Paid' }] }
const R4 = { id: 'd', date: '2025-12-02', vendor: 'Staples', order_number: '', total: 20, items: ['Ink'], rows: [{ category: 'Printing & Copying', amount: 20, statusLabel: 'Reimbursed', stageLabel: 'Reimbursed or Paid' }] }

test('Filed groups by month newest first, and a split receipt counts in each category for what it spent there', () => {
  const months = M.filedFolders([R1, R2, R3, R4], { groupBy: 'month' })
  assert.deepEqual(months.map(f => [f.key, f.count, f.total]), [['September 2026', 2, 549.82], ['July 2026', 1, 350], ['December 2025', 1, 20]])
  assert.deepEqual(months[0].entries.map(e => e.receipt.id), ['b', 'a'], 'newest first inside a folder')
  const cats = M.filedFolders([R1, R2, R3], { groupBy: 'category' })
  assert.deepEqual(cats.map(f => [f.key, f.count, f.total]), [['Meals & Catering', 1, 496.33], ['Printing & Copying', 1, 38.99], ['Supplies & Materials', 2, 364.5]])
  assert.equal(cats.find(f => f.key === 'Printing & Copying').entries[0].part, 38.99)
  assert.equal(cats.find(f => f.key === 'Meals & Catering').entries[0].part, null, 'a single-category receipt is not split')
  const sum = cats.reduce((a, f) => a + f.total, 0)
  assert.equal(Math.round(sum * 100), Math.round((R1.total + R2.total + R3.total) * 100), 'the category folders add up to the receipts')
  assert.deepEqual(M.filedFolders([R1, R2, R3], { groupBy: 'vendor' }).map(f => [f.key, f.count]), [['Amazon', 2], ['Beverly Grove Catering', 1]])
  // BUDGET-FIXES-1 release 2 changed this: Filed groups by Stage, the Sheet's one word (was Status).
  assert.deepEqual(M.filedFolders([R1, R2, R3], { groupBy: 'status' }).map(f => f.key), ['Receipt attached', 'Reimbursed or Paid', 'Submitted to Concur'])
  assert.deepEqual(M.filedFolders([R1, R2, R3], { query: 'notebook' }).map(f => f.entries.map(e => e.receipt.id)), [['c']], 'search reads items')
  assert.deepEqual(M.filedFolders([R1, R2, R3], { query: 'INV-206' }).map(f => f.key), ['September 2026'], 'and order numbers')
})

test('a folded slip says what it needs in a few words', () => {
  const chk = (checks, duplicate = null) => ({ checks, duplicate })
  assert.deepEqual(M.slipState(chk([{ key: 'split', tone: 'info' }]), 2), { tone: 'info', text: '2 rows · ready' })
  assert.deepEqual(M.slipState(chk([{ key: 'x', tone: 'warn' }]), 1), { tone: 'warn', text: '1 row · 1 warning' })
  assert.deepEqual(M.slipState(chk([{ key: 'rule:meals_documentation', tone: 'block' }]), 1), { tone: 'warn', text: 'Needs purpose and attendees' })
  assert.deepEqual(M.slipState(chk([{ key: 'not_started', tone: 'block', text: 'FY28 hasn’t started.' }]), 1), { tone: 'warn', text: 'Start FY28' })
  assert.deepEqual(M.slipState(chk([], { expense: { row_label: 'FY26 row 4' } }), 1), { tone: 'warn', text: 'Matches FY26 row 4' })
})

// ── The server's filed list, on Postgres ────────────────────────────────────────

test('the filed list is the year’s accepted receipts with the rows they posted, read live', async () => {
  const pg = new PGlite()
  await pg.exec(read('test/fixtures/budgetReceiptsPrelude.sql'))
  const { rows: [owner] } = await pg.query(`INSERT INTO user_profiles (full_name, email, role, is_owner) VALUES ('Jester Lloyd Bautista', 'j@x.org', 'owner', true) RETURNING *`)
  for (const m of ['20261009000000_program_budget_phase_a', '20261010000000_budget_subscription_approval', '20261011000000_budget_subscription_cells', '20261012000000_budget_expense_zero_quantity', '20261013000000_budget_receipts'])
    await pg.exec(runnable(read(`supabase/migrations/${m}.sql`)))
  await pg.exec(runnable(read('db/migrations/seed_program_budget_fy26.sql')))
  const db = pgliteRest(pg)
  await E.startYear(db, owner, { fy: 2027, total: 40000, cost_center: 'Nursing Education', plan: 'none', today: TODAY })
  await pg.query(`UPDATE keith_skills SET status = 'active', enabled = true, version = 1 WHERE slug = 'read-receipt'`)
  const reading = { vendor: 'Amazon', order_number: '112-7730158-4402217', date: '2026-09-03', card_last4: '', subtotal: 53.49, tax: 0, shipping: 0, tip: 0, total: 53.49, has_shipping_address: true, unreadable_fields: [],
    lines: [{ item: 'Copy Paper', quantity: 1, amount: 38.99, category: 'Printing & Copying', confidence: 'high', reason: 'Paper.' }, { item: 'Name Badge Labels', quantity: 2, amount: 14.5, category: 'Supplies & Materials', confidence: 'high', reason: 'Labels.' }] }
  const { receipt, upload } = await R.startUpload(db, owner, { fileName: 'a.jpg', contentType: 'image/jpeg', size: 3 })
  await db.storage.from(R.RECEIPT_BUCKET).upload(upload.path, Buffer.from('abc'))
  const read1 = await R.readReceipt(db, owner, { id: receipt.id, complete: async () => ({ ok: true, text: JSON.stringify(reading), model: 'm', usage: {} }), today: TODAY })
  const acc = await R.acceptReceipt(db, owner, { id: receipt.id, draft: { ...read1.receipt.draft, payment_method: 'personal_concur' }, today: TODAY })
  const [filed] = await R.filedReceipts(db, { fy: 2027, today: TODAY })
  assert.deepEqual([filed.vendor, filed.total, filed.items, filed.decided_by, filed.filed_name], ['Amazon', 53.49, ['Copy Paper', 'Name Badge Labels'], 'Jester Lloyd Bautista', acc.filed_name])
  assert.deepEqual(filed.rows.map(r => [r.row_label, r.category, r.amount, r.statusLabel, r.payment]), [
    ['FY27 row 1', 'Printing & Copying', 38.99, 'Recorded', 'Personal (Concur)'], ['FY27 row 2', 'Supplies & Materials', 14.5, 'Recorded', 'Personal (Concur)']])
  assert.deepEqual(await R.filedReceipts(db, { fy: 2026, today: TODAY }), [], 'a year holds only its own receipts')
  // A row changed in the Sheet shows its change here; a deleted one drops out.
  await E.updateExpense(db, owner, { id: filed.rows[0].id, patch: { status: 'submitted' }, today: TODAY })
  await E.deleteExpenses(db, owner, { ids: [filed.rows[1].id] })
  const [again] = await R.filedReceipts(db, { fy: 2027, today: TODAY })
  assert.deepEqual(again.rows.map(r => r.statusLabel), ['Submitted'])
})

// ── Wiring and render ───────────────────────────────────────────────────────────

test('every folder starts closed and closes again when the grouping changes (Owner)', () => {
  const src = read('src/components/budget/BudgetFiled.jsx')
  assert.match(src, /const \[open, setOpen\] = useState\(\(\) => new Set\(\)\)/)
  assert.match(src, /const regroup = \(g\) => \{ setGroupBy\(g\); setOpen\(new Set\(\)\) \}/)
  // RECEIPTS-REDESIGN-1 (2 of 3) changed this: a closed folder is a tan card with up to five small
  // receipts, each with its LATE or SOON tab. Still closed by default, still closed by a regroup.
  assert.match(src, /className="bud-fcard bud-holder" aria-expanded="false"/)
  assert.match(src, /f\.entries\.slice\(0, 5\)\.map\(e => \(/, 'five receipts shown')
  assert.match(src, /<ReceiptPaper proposal=\{e\.receipt\.proposal\} size="xs" \/>/)
  assert.match(read('api/budget-staff.js'), /receipts_filed: \['action', 'fiscal_year'\]/)
  assert.doesNotMatch(read('api/budget-staff.js'), /READS = new Set\(\[[^\]]*receipts_filed/, 'Owner only')
})

test('a filed receipt has no frame: the paper itself lifts on hover and focus', () => {
  const css = read('src/components/budget/budget.css')
  // RECEIPTS-REDESIGN-1 (2 of 3) changed this: the paper sits at a slight fixed tilt (--tilt) and lifts
  // straight up, and its wrapper is the anchor for the stamp and the LATE tab.
  assert.match(css, /\.bud-ftile:hover \.bud-rcpt, \.bud-ftile:focus-visible \.bud-rcpt \{ transform: translateY\(-4px\);/)
  assert.match(css, /\.bud-ftile-paper \{ position: relative; display: grid; justify-items: center; padding: 12px 4px 4px; min-width: 0; transform: rotate\(var\(--tilt, 0deg\)\); \}/, 'no background or border on the holder')
  // KPI-PAD-1 (Owner, 2026-09-27: the KPI cards' contents sat on their edges): the receipt tile first
  // shipped as .bud-tile, the KPI card's own class, and its padding: 0 won. The KPI card is the only
  // .bud-tile rule with a padding, and the filed tile never uses that name again.
  assert.deepEqual(css.match(/^\.bud-tile \{[^}]*\}/gm), ['.bud-tile { padding: 14px 16px; display: flex; flex-direction: column; gap: 4px; min-width: 0; }'])
  assert.doesNotMatch(read('src/components/budget/BudgetFiled.jsx'), /"bud-tile["-]/)
  assert.match(css, /\.bud-modal-back \{ position: fixed; inset: 0; z-index: 2100;/, 'View original opens above the side panel')
})

let vite, P
before(async () => {
  vite = await createServer({ server: { middlewareMode: true, hmr: false, ws: false }, appType: 'custom', logLevel: 'error' })
  P = await vite.ssrLoadModule('/src/components/budget/ReceiptSlip.jsx')
})
after(async () => { await vite?.close() })

test('the drawn receipt prints the vendor’s logo, and the thumbnails leave out order, card and address', () => {
  const p = M.parseReading(JSON.stringify({ vendor: 'Amazon', order_number: '112-7730158', date: '2026-09-03', card_last4: '4417', subtotal: 10, tax: 0, total: 10, has_shipping_address: true,
    lines: [{ item: 'Paper', quantity: 1, amount: 10, category: 'Printing & Copying', confidence: 'high', reason: 'x' }] }), ['Printing & Copying'])
  const lg = renderToStaticMarkup(React.createElement(P.ReceiptPaper, { proposal: p }))
  assert.match(lg, /class="bud-rcpt bud-rcpt-lg bud-rcpt-logo" role="img"/)
  assert.match(lg, /<img src="\/vendor-logos\/amazon\.png" alt="" loading="lazy" draggable="false"\/>/)
  assert.match(lg, /Order #112-7730158/)
  const sm = renderToStaticMarkup(React.createElement(P.ReceiptPaper, { proposal: p, size: 'sm' }))
  assert.match(sm, /bud-rcpt-sm/)
  assert.match(sm, /aria-hidden="true"/)
  assert.doesNotMatch(sm, /Order #|Card|Ship to/)
  const none = renderToStaticMarkup(React.createElement(P.ReceiptPaper, { proposal: { ...p, vendor: 'Beverly Grove Catering' } }))
  assert.doesNotMatch(none, /<img/)
  assert.match(none, /Beverly Grove Catering/)
})
