// api/webhooks/resend.js
// Receives delivery/engagement events from Resend and updates notification_log.
// Requires RESEND_WEBHOOK_SECRET env var (generated by Resend dashboard when webhook is configured).
//
// ASPIRE MESSAGES, PHASE 2 (STAGE B): additionally reconciles
// message_notification_deliveries.provider_status by resend_email_id. This only
// advances provider_status (monotonically, never downgraded) and NEVER touches
// queue_status, never retries, and never reads or writes a message body. The
// existing notification_log behavior below is unchanged.
//
// S-21 (S21-1, 2026-09-26): three rules the webhook keeps, in decideNotificationUpdate.
//   1. A terminal status (bounced, complained, failed) is never overwritten.
//   2. A status only moves UP the ranking; a same-rank or lower event is a no-op for the
//      status, and delivery_delayed ranks BELOW delivered so a late "delayed" cannot
//      overwrite a delivery.
//   3. A timestamp column is written once, when it is null; a later event never rewrites it.
// Replay: every event Svix delivers carries a unique svix-id header, which the signature
// covers. The ids already applied to a row are kept in notification_log.metadata
// (webhook_event_ids, most recent WEBHOOK_EVENT_ID_KEEP), and the update is a
// compare-and-set that refuses a row already holding the id, so a replay, even a
// concurrent one, is acknowledged and changes nothing. No table was added for this.

/* global process, Buffer */

import { createClient } from '@supabase/supabase-js';
import { Webhook } from 'svix';
import { shouldApplyProviderStatus } from '../../lib/server/messages/deliveryLogic.js';

// Resend event type -> message_notification_deliveries.provider_status.
const DELIVERY_PROVIDER_MAP = {
  'email.sent':       'sent',
  'email.delivered':  'delivered',
  'email.opened':     'opened',
  'email.clicked':    'clicked',
  'email.bounced':    'bounced',
  'email.complained': 'complained',
};

// Reconcile the Messages delivery row (if any) for this Resend id. Best-effort
// and non-fatal: a failure here never blocks the notification_log path. Updates
// provider_status only, using the monotonic guard; queue_status is untouched.
async function reconcileMessageDelivery(supabase, resendEmailId, eventType) {
  const providerStatus = DELIVERY_PROVIDER_MAP[eventType];
  if (!providerStatus) return;
  try {
    const { data: row } = await supabase
      .from('message_notification_deliveries')
      .select('id, provider_status')
      .eq('resend_email_id', resendEmailId)
      .maybeSingle();
    if (!row) return;
    if (!shouldApplyProviderStatus(row.provider_status, providerStatus)) return;
    await supabase
      .from('message_notification_deliveries')
      .update({ provider_status: providerStatus, updated_at: new Date().toISOString() })
      .eq('id', row.id);
  } catch (err) {
    console.error('[resend-webhook] message delivery reconcile failed (non-fatal):', err?.message);
  }
}

// ACTION-CENTER-1: delivery is an in-app fact for the staff member who sent it.
// A bulk send shares one batch correlation across recipient rows, so the first
// delivered webhook creates the one summary and later deliveries are idempotent.
async function emitOutreachDelivered(supabase, logRow) {
  if (!['direct_message_sent', 'bulk_message_sent'].includes(logRow?.notification_type)) return;
  const senderId = logRow?.metadata?.sent_by_user_id;
  if (!senderId) return;
  try {
    const { data: recipient } = await supabase.from('user_profiles')
      .select('id,email,is_active').eq('id', senderId).maybeSingle();
    if (!recipient || recipient.is_active === false || !String(recipient.email || '').trim()) return;
    const batchId = logRow.notification_type === 'bulk_message_sent' ? logRow?.metadata?.batch_id : null;
    const correlationId = batchId ? `outreach-delivered:batch:${batchId}` : `outreach-delivered:direct:${logRow.id}`;
    const subject = batchId
      ? `Bulk outreach delivered: ${logRow.subject || 'Untitled message'}`
      : `Outreach delivered: ${logRow.subject || 'Untitled message'}`;
    const { error } = await supabase.from('staff_notifications').insert({
      correlation_id: correlationId,
      recipient_profile_id: recipient.id,
      recipient_email: recipient.email,
      event_type: 'outreach_delivered',
      actor_name: 'Delivery service',
      actor_role: 'system',
      subject,
      dest_url: '/connect/outreach',
      queue_status: 'suppressed',
    });
    if (error && String(error.code) !== '23505') throw error;
  } catch (err) {
    // Best effort: webhook reconciliation remains authoritative even if the
    // optional in-app notification cannot be written.
    if (String(err?.code) !== '23505') console.error('[resend-webhook] outreach notification failed (non-fatal):', err?.message);
  }
}

let cachedDb = null;
function defaultDb() {
  if (!cachedDb) {
    cachedDb = createClient(
      process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY
    );
  }
  return cachedDb;
}

// Resend event type → notification_log status + optional timestamp column to update
const EVENT_MAP = {
  'email.sent':             { status: 'sent',       timestampCol: 'sent_at' },
  'email.delivered':        { status: 'delivered',  timestampCol: 'delivered_at' },
  'email.opened':           { status: 'opened',     timestampCol: 'opened_at' },
  'email.clicked':          { status: 'clicked',    timestampCol: 'clicked_at' },
  'email.bounced':          { status: 'bounced',    timestampCol: 'bounced_at' },
  'email.complained':       { status: 'complained', timestampCol: 'complained_at' },
  'email.delivery_delayed': { status: 'delayed' },  // no dedicated column; status only
};

// Status precedence. A status only ever moves UP; equal rank is a no-op. delayed sits
// below delivered on purpose (S-21): Resend can report a delay before the delivery it
// then reports, and the two may arrive in either order.
export const STATUS_RANK = {
  queued:    0,
  sent:      1,
  delayed:   2,
  delivered: 3,
  opened:    4,
  clicked:   5,
  bounced:   6,    // terminal
  complained:6,    // terminal
  failed:    6,    // terminal
};
export const TERMINAL_STATUSES = new Set(['bounced', 'complained', 'failed']);
const TIMESTAMP_COLUMNS = [...new Set(Object.values(EVENT_MAP).map(e => e.timestampCol).filter(Boolean))];
export const WEBHOOK_EVENT_ID_KEEP = 50;
const SVIX_ID_RE = /^[A-Za-z0-9_.-]{1,120}$/;

// S-21: the pure decision. Given the row as it is and the event, return the columns to
// write, or null when the event changes nothing. Never downgrades, never overwrites a
// terminal status, never rewrites a timestamp that is already set.
export function decideNotificationUpdate({ row, eventStatus, timestampCol, eventTime }) {
  const payload = {};
  const currentStatus = row?.status;
  const currentRank = STATUS_RANK[currentStatus] ?? 0;
  const newRank     = STATUS_RANK[eventStatus] ?? 0;
  if (!TERMINAL_STATUSES.has(currentStatus) && newRank > currentRank) {
    payload.status = eventStatus;
  }
  if (timestampCol && row?.[timestampCol] == null) {
    payload[timestampCol] = eventTime;
  }
  return Object.keys(payload).length > 0 ? payload : null;
}

function seenEventIds(metadata) {
  const ids = metadata && typeof metadata === 'object' ? metadata.webhook_event_ids : null;
  return Array.isArray(ids) ? ids.filter(x => typeof x === 'string') : [];
}

export const config = {
  api: { bodyParser: false },  // raw body required for Svix signature verification
};

async function getRawBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', chunk => chunks.push(chunk));
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

export default async function handler(req, res) {
  return productionHandler(req, res);
}

export function createResendWebhookHandler({
  getDb = defaultDb,
  getSecret = () => process.env.RESEND_WEBHOOK_SECRET,
  readBody = getRawBody,
  now = () => new Date(),
} = {}) {
  return async function resendWebhookHandler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Read raw body before any parsing
  let rawBody;
  try {
    rawBody = await readBody(req);
  } catch (err) {
    console.error('[resend-webhook] failed to read body:', err);
    return res.status(400).json({ error: 'Invalid body' });
  }

  // Verify Svix signature
  const webhookSecret = getSecret();
  if (!webhookSecret) {
    console.error('[resend-webhook] RESEND_WEBHOOK_SECRET not configured');
    return res.status(500).json({ error: 'Webhook secret not configured' });
  }

  let event;
  try {
    const wh = new Webhook(webhookSecret);
    event = wh.verify(rawBody, {
      'svix-id':        req.headers['svix-id'],
      'svix-timestamp': req.headers['svix-timestamp'],
      'svix-signature': req.headers['svix-signature'],
    });
  } catch (err) {
    console.error('[resend-webhook] signature verification failed:', err.message);
    return res.status(401).json({ error: 'Invalid signature' });
  }

  const supabase = getDb();
  const rawSvixId = String(req.headers['svix-id'] || '');
  const svixId = SVIX_ID_RE.test(rawSvixId) ? rawSvixId : null;

  const { type, data } = event;
  const eventConfig = EVENT_MAP[type];

  // Acknowledge unknown event types - Resend may add new types over time
  if (!eventConfig) {
    console.log(`[resend-webhook] unhandled event type: ${type}`);
    return res.status(200).json({ success: true, handled: false });
  }

  const resendEmailId = data?.email_id;
  if (!resendEmailId) {
    console.warn(`[resend-webhook] ${type} missing email_id, skipping`);
    return res.status(200).json({ success: true, handled: false });
  }

  try {
    // Look up the matching notification_log row by resend_email_id, with the timestamp
    // columns (written once each) and the metadata that records applied event ids.
    const { data: logRow, error: lookupErr } = await supabase
      .from('notification_log')
      .select(`id, status, notification_type, subject, metadata, ${TIMESTAMP_COLUMNS.join(', ')}`)
      .eq('resend_email_id', resendEmailId)
      .maybeSingle();

    if (lookupErr) {
      console.error('[resend-webhook] lookup failed:', lookupErr);
      return res.status(500).json({ error: 'Database lookup failed' });
    }

    // S-21 replay: an event id this row has already applied changes nothing, anywhere.
    const seen = seenEventIds(logRow?.metadata);
    if (svixId && logRow && seen.includes(svixId)) {
      console.log(`[resend-webhook] ${type} replay for ${resendEmailId} acknowledged, no change`);
      return res.status(200).json({ success: true, handled: false, reason: 'replayed' });
    }

    // ASPIRE MESSAGES: reconcile the Messages delivery row (provider_status only,
    // monotonic, best-effort). Runs independently of the notification_log path.
    await reconcileMessageDelivery(supabase, resendEmailId, type);

    if (!logRow) {
      // Email sent before webhooks were wired up, or a manual Resend dashboard send
      console.log(`[resend-webhook] no log row for resend_email_id ${resendEmailId} (${type}), acknowledged`);
      return res.status(200).json({ success: true, handled: false, reason: 'not_found' });
    }

    const decided = decideNotificationUpdate({
      row: logRow,
      eventStatus: eventConfig.status,
      timestampCol: eventConfig.timestampCol,
      eventTime: data?.created_at || now().toISOString(),
    });

    // Record the event id on the row whether or not the event moved anything, so the
    // same id arriving again is a replay. The update is a compare-and-set on the id: a
    // concurrent duplicate loses the race and matches no row.
    const updatePayload = { ...(decided || {}) };
    if (svixId) {
      const metadata = logRow.metadata && typeof logRow.metadata === 'object' && !Array.isArray(logRow.metadata) ? logRow.metadata : {};
      updatePayload.metadata = { ...metadata, webhook_event_ids: [...seen, svixId].slice(-WEBHOOK_EVENT_ID_KEEP) };
    }

    if (Object.keys(updatePayload).length > 0) {
      let query = supabase
        .from('notification_log')
        .update(updatePayload)
        .eq('id', logRow.id);
      if (svixId) {
        query = query.or(`metadata->webhook_event_ids.is.null,metadata->webhook_event_ids.not.cs.${JSON.stringify([svixId])}`);
      }
      const { data: updated, error: updateErr } = await query.select('id');

      if (updateErr) {
        console.error('[resend-webhook] update failed:', updateErr);
        return res.status(500).json({ error: 'Database update failed' });
      }
      if (svixId && (!updated || updated.length === 0)) {
        console.log(`[resend-webhook] ${type} concurrent replay for ${resendEmailId} acknowledged, no change`);
        return res.status(200).json({ success: true, handled: false, reason: 'replayed' });
      }

      console.log(`[resend-webhook] ${type} for ${resendEmailId} applied:`, decided ? Object.keys(decided) : 'no status change');
    }

    if (type === 'email.delivered' && decided?.status === 'delivered') await emitOutreachDelivered(supabase, logRow);

    return res.status(200).json({ success: true, handled: true, changed: !!decided });
  } catch (err) {
    console.error('[resend-webhook] processing error:', err);
    return res.status(500).json({ error: 'Processing failed' });
  }
  };
}

const productionHandler = createResendWebhookHandler();
