// api/webhooks/resend.js
// Receives delivery/engagement events from Resend and updates notification_log.
// Requires RESEND_WEBHOOK_SECRET env var (generated by Resend dashboard when webhook is configured).

import { createClient } from '@supabase/supabase-js';
import { Webhook } from 'svix';

const supabase = createClient(
  process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

// Resend event type → notification_log status + optional timestamp column to update
const EVENT_MAP = {
  'email.sent':             { status: 'sent',       timestampCol: 'sent_at' },
  'email.delivered':        { status: 'delivered',  timestampCol: 'delivered_at' },
  'email.opened':           { status: 'opened',     timestampCol: 'opened_at' },
  'email.clicked':          { status: 'clicked',    timestampCol: 'clicked_at' },
  'email.bounced':          { status: 'bounced',    timestampCol: 'bounced_at' },
  'email.complained':       { status: 'complained', timestampCol: 'complained_at' },
  'email.delivery_delayed': { status: 'delayed' },  // no dedicated column; status only
};

// Status precedence — never downgrade. Higher rank = more authoritative.
const STATUS_RANK = {
  queued:    0,
  sent:      1,
  delivered: 2,
  delayed:   2,
  opened:    3,
  clicked:   4,
  bounced:   5,    // terminal
  complained:5,    // terminal
  failed:    5,
};

export const config = {
  api: { bodyParser: false },  // raw body required for Svix signature verification
};

async function getRawBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', chunk => chunks.push(chunk));
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Read raw body before any parsing
  let rawBody;
  try {
    rawBody = await getRawBody(req);
  } catch (err) {
    console.error('[resend-webhook] failed to read body:', err);
    return res.status(400).json({ error: 'Invalid body' });
  }

  // Verify Svix signature
  const webhookSecret = process.env.RESEND_WEBHOOK_SECRET;
  if (!webhookSecret) {
    console.error('[resend-webhook] RESEND_WEBHOOK_SECRET not configured');
    return res.status(500).json({ error: 'Webhook secret not configured' });
  }

  let event;
  try {
    const wh = new Webhook(webhookSecret);
    event = wh.verify(rawBody, {
      'svix-id':        req.headers['svix-id'],
      'svix-timestamp': req.headers['svix-timestamp'],
      'svix-signature': req.headers['svix-signature'],
    });
  } catch (err) {
    console.error('[resend-webhook] signature verification failed:', err.message);
    return res.status(401).json({ error: 'Invalid signature' });
  }

  const { type, data } = event;
  const eventConfig = EVENT_MAP[type];

  // Acknowledge unknown event types — Resend may add new types over time
  if (!eventConfig) {
    console.log(`[resend-webhook] unhandled event type: ${type}`);
    return res.status(200).json({ success: true, handled: false });
  }

  const resendEmailId = data?.email_id;
  if (!resendEmailId) {
    console.warn(`[resend-webhook] ${type} missing email_id, skipping`);
    return res.status(200).json({ success: true, handled: false });
  }

  try {
    // Look up the matching notification_log row by resend_email_id
    const { data: logRow, error: lookupErr } = await supabase
      .from('notification_log')
      .select('id, status')
      .eq('resend_email_id', resendEmailId)
      .maybeSingle();

    if (lookupErr) {
      console.error('[resend-webhook] lookup failed:', lookupErr);
      return res.status(500).json({ error: 'Database lookup failed' });
    }

    if (!logRow) {
      // Email sent before webhooks were wired up, or a manual Resend dashboard send
      console.log(`[resend-webhook] no log row for resend_email_id ${resendEmailId} (${type}) — acknowledged`);
      return res.status(200).json({ success: true, handled: false, reason: 'not_found' });
    }

    // Build update payload — always set the timestamp, update status only if higher rank
    const updatePayload = {};

    if (eventConfig.timestampCol) {
      updatePayload[eventConfig.timestampCol] = data?.created_at || new Date().toISOString();
    }

    const currentRank = STATUS_RANK[logRow.status] ?? 0;
    const newRank     = STATUS_RANK[eventConfig.status] ?? 0;
    if (newRank >= currentRank) {
      updatePayload.status = eventConfig.status;
    }

    if (Object.keys(updatePayload).length > 0) {
      const { error: updateErr } = await supabase
        .from('notification_log')
        .update(updatePayload)
        .eq('id', logRow.id);

      if (updateErr) {
        console.error('[resend-webhook] update failed:', updateErr);
        return res.status(500).json({ error: 'Database update failed' });
      }

      console.log(`[resend-webhook] ${type} → ${resendEmailId} updated:`, updatePayload);
    }

    return res.status(200).json({ success: true, handled: true });
  } catch (err) {
    console.error('[resend-webhook] processing error:', err);
    return res.status(500).json({ error: err.message });
  }
}
