#!/usr/bin/env python3
"""
scripts/prepare_vendor_logos.py

RECEIPT-ORGANIZER-1 (Owner, 2026-09-27): a vendor's logo is printed at the top of its drawn receipt
in Program Budget > Receipts, black and white, like a receipt printer's. This turns the Owner's logo
files into that print and writes the list the app reads:

    python3 scripts/prepare_vendor_logos.py <folder of logo files>

For each PNG/JPEG/WebP in the folder it writes public/vendor-logos/<slug>.png: trimmed to the mark,
96px tall, one ink (#111) on transparent. Dark and coloured parts print; white parts stay paper, so
white lettering on a coloured badge survives. The slug comes from the file name, less the download
site's suffix and words like "Logo", "Wordmark" or "Colored" ("amazon@logotyp.us.png" -> amazon,
"Vercel Logo - Colored - 1288x256 - zonalogo.com.png" -> vercel). Then it rewrites
src/lib/budget/vendorLogos.js with every slug in public/vendor-logos, which is how the app knows a logo
exists without asking the server for one that does not. Needs Pillow (python3 -m pip install pillow).
"""
import os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'public', 'vendor-logos')
LIST = os.path.join(ROOT, 'src', 'lib', 'budget', 'vendorLogos.js')
HEIGHT, INK = 96, (17, 17, 17)

def slug(name):
    n = os.path.splitext(name)[0].split('@')[0].split(' - ')[0]
    n = re.sub(r'(?i)\b(logo|icon|wordmark|black|colored|coloured|white)\b', ' ', n.replace('-', ' ').replace('_', ' '))
    return re.sub(r'[^a-z0-9]+', '-', n.lower()).strip('-')

def convert(path):
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    ink = Image.new('L', (w, h), 0)
    src, dst = im.load(), ink.load()
    for y in range(h):
        for x in range(w):
            r, g, b, a = src[x, y]
            if a:
                lum = 0.299 * r + 0.587 * g + 0.114 * b
                dst[x, y] = int(a * min(1, max(0, (240 - lum) / 50)))
    box = ink.getbbox()
    if not box:
        return None
    ink = ink.crop(box)
    width = max(1, round(ink.width * HEIGHT / ink.height))
    ink = ink.resize((width, HEIGHT), Image.LANCZOS)
    out = Image.new('RGBA', (width, HEIGHT), INK + (255,))
    out.putalpha(ink)
    return out

def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    src = sys.argv[1]
    os.makedirs(OUT, exist_ok=True)
    for f in sorted(os.listdir(src)):
        if not f.lower().endswith(('.png', '.jpg', '.jpeg', '.webp')):
            continue
        s = slug(f)
        out = convert(os.path.join(src, f))
        if not s or out is None:
            print(f'skipped {f}: nothing to print')
            continue
        out.save(os.path.join(OUT, f'{s}.png'), optimize=True)
        print(f'{f} -> public/vendor-logos/{s}.png ({out.width}x{out.height})')
    slugs = sorted(os.path.splitext(f)[0] for f in os.listdir(OUT) if f.endswith('.png'))
    with open(LIST, 'w') as fh:
        fh.write('// src/lib/budget/vendorLogos.js\n//\n')
        fh.write('// GENERATED by scripts/prepare_vendor_logos.py: the vendor logos in public/vendor-logos, by slug.\n')
        fh.write('// Do not edit by hand; add a logo file and run the script.\n')
        fh.write('export const VENDOR_LOGOS = Object.freeze([\n')
        for s in slugs:
            fh.write(f"  '{s}',\n")
        fh.write('])\n')
    print(f'{len(slugs)} logos listed in src/lib/budget/vendorLogos.js')

if __name__ == '__main__':
    main()
