// src/lib/budget/vendorLogos.js
//
// GENERATED by scripts/prepare_vendor_logos.py: the vendor logos in public/vendor-logos, by slug.
// Do not edit by hand; add a logo file and run the script.
export const VENDOR_LOGOS = Object.freeze([
  'amazon',
  'anthropic',
  'best-buy',
  'canva',
  'costco',
  'fedex',
  'flodesk',
  'grok-xai',
  'home-depot',
  'michaels-stores',
  'office-depot',
  'openai',
  'resend',
  'supabase',
  'vercel',
  'walmart',
])
